### ISSUE TITLE
Internalize input variable processing

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#32]
Currently (e7b204fbc6b52b60abd6aa76cc3d8fe71e58e7ae v1.1) there are a few annoying manual steps to, e.g., turn application method into a set of dummy variables. Should create a helper function that can do this automatically. One issue is lack of input in return()ed result, so no straightforward way to check on variable processing.

**Comment by sashahafner** [comment]
Now in release v1.5.0.

**Comment by sashahafner** [comment]
We need to see if the Danish names in prepDat() work after dealing with the non-ASCII character issue in 671342a43699a1facb3114f52f802736165a24cc

![image](https://user-images.githubusercontent.com/35272876/140641524-b38550a3-7d2e-42be-84f9-34fb746b14bf.png)

There is some code in the vignette that can be tweaked for checking (search for prep = TRUE to find it).

Are there other aliases we should add for application methods etc.? German or French terms?

**Comment by ChHaeni** [comment]
- [ ] change `value = 'dummy'` to `keep.original = FALSE`? (Or is the idea to provide additional output formats?)
- [ ] give error if entry does not match any valid value
- [ ] guess also column names (and "correct" them to match pars)? (e.g. `man.source`, `man.type`, `manure`, etc.)

**Comment by ChHaeni** [comment]
- [ ] add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)

**Comment by ChHaeni** [comment]
- [ ] add option to keep original column names or replace by default (default)
- [ ] add option to keep original level names or replace by default (default)

**Comment by sashahafner** [comment]
>  change value = 'dummy' to keep.original = FALSE? (Or is the idea to provide additional output formats?)
I think we should remove this argument, and have the function always return the dummies only. See #36.

**Comment by sashahafner** [comment]
> give error if entry does not match any valid value

Yes. So `prepDat()` throws an error telling the user there is nothing to convert into dummy variables. Could do this with `ndum == 0`.

**Comment by sashahafner** [comment]
> guess also column names (and "correct" them to match pars)? (e.g. man.source, man.type, manure, etc.)

I would rather not. Could be a lot of work, and easily end up more of a problem than a help by correcting the wrong variables.

**Comment by sashahafner** [comment]
>  handle factors

I don't understand.

**Comment by sashahafner** [comment]
> remove ndum

Why? The approach in the code is kind of crude. Would be nice to have something more straightforward, e.g., separate dum from dat from the start? I'm open to ideas here.

**Comment by sashahafner** [comment]
> add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)

Good idea, but I am not sure it is worth the effort. I was not planning on exporting this function or even providing access to the arguments through the core model function. Do you think we should?

**Comment by sashahafner** [comment]
> add option to keep original column names or replace by default (default)
> add option to keep original level names or replace by default (default)

I guess these depend on what we decide to do with the earlier suggestions.

**Comment by ChHaeni** [comment]
> > give error if entry does not match any valid value
> 
> Yes. So `prepDat()` throws an error telling the user there is nothing to convert into dummy variables. Could do this with `ndum == 0`.

Hmm, I was misunderstanding the purpose of this function initially. 
I guess, if we want to throw errors, we also need to check if the defaults ('cattle slurry', etc..) are provided correctly, i.e. extend the current 'dictionnaries' in `prepDat`..?

**Comment by ChHaeni** [comment]
> > guess also column names (and "correct" them to match pars)? (e.g. man.source, man.type, manure, etc.)
> 
> I would rather not. Could be a lot of work, and easily end up more of a problem than a help by correcting the wrong variables.

I still like the idea and have a suggestion already... Will open PR soon...

**Comment by ChHaeni** [comment]
> > handle factors
> 
> I don't understand.

These points were rather intended as a todo/reminder list for myself :) 
But I was thinking of possible issues when checking for matching names, if a user provides a column with factors instead of character values...

**Comment by ChHaeni** [comment]
> > add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)
> 
> Good idea, but I am not sure it is worth the effort. I was not planning on exporting this function or even providing access to the arguments through the core model function. Do you think we should?

I think this depends on how we end up with the prepDat function. As I understand it now, the `xzy.levels` arguments are not used at all, since the function will not be exported and we could hard-code the dictionnaries in the function ifself..?

**Comment by ChHaeni** [comment]
> > add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)
> 
> Good idea, but I am not sure it is worth the effort. I was not planning on exporting this function or even providing access to the arguments through the core model function. Do you think we should?

In my opinion, we can leave it unexported, which makes things also easier. 

I would even go further and remove the `prep` argument. I think this should be `TRUE` anyway and any already existing "prepared" columns should be passed silently...

**Comment by sashahafner** [comment]
> > > add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)
> > 
> > 
> > Good idea, but I am not sure it is worth the effort. I was not planning on exporting this function or even providing access to the arguments through the core model function. Do you think we should?
> 
> I think this depends on how we end up with the prepDat function. As I understand it now, the `xzy.levels` arguments are not used at all, since the function will not be exported and we could hard-code the dictionnaries in the function ifself..?

Hmm, I am not sure we understand each other. In the current version, this `bc` vector, for example,
``` 
                   app.mthd.levels = list(ts = 'ts', 
                                           bc = c('broadcast', 'bc', 'broadspread', 'bredspredning', 'bredspredt'), ...
 ```
gives the user flexibility. A data frame column like this:

```
app.mthd # Column name
bc
broadcast
broadspread
trailing hose
```
would result in this
```
app.mthd    app.mthd.bc
bc                       1
broadcast           1
broadspread       1
trailing hose        0
```

Normally a user wouldn't mix different names for the same application method, but the point is the bc vector in the app.mthd.levels argument includes all allowed values that will be interpreted as broadcast. So they are used, but if we don't export it, cannot be set by a user. More on exporting in comment below.

**Comment by sashahafner** [comment]
> > > add "level dictionaries"? (i.e. remove default values for *.levels arguments and get them from a "dictionary", keep *.levels arguments to provide additional user-defined levels)
> > 
> > 
> > Good idea, but I am not sure it is worth the effort. I was not planning on exporting this function or even providing access to the arguments through the core model function. Do you think we should?
> 
> In my opinion, we can leave it unexported, which makes things also easier.
> 
> I would even go further and remove the `prep` argument. I think this should be `TRUE` anyway and any already existing "prepared" columns should be passed silently...

OK good on not exporting! Although I could see a case where a user might have some other names they would like to use, I don't think the extra flexibility or convenience is balanced by the added complexity (including new arguments in the core function) and additional opportunity for making mistakes.

I am still unsure of whether to remove the prep argument though. I'm thinking about backwards compatibility with my old code but also about how much I hate software that is "too helpful" (e.g., Excel incrementing numbers by 1 when copying down a column, or RStudio deciding whether I really want a ")" or not). Maybe a user could have columns with names that happen to match, but that are not intended for use for setting up dummy variables. 

I'll think about it a bit more.

**Comment by sashahafner** [comment]
Around 68f50c033af348fb8e0e7c351533bdf4bbfabb4c this argument is `TRUE` by default (now called `prep.dum` because of a new `prep.incorp` argument)

**Comment by sashahafner** [comment]
I think the behavior is explained clearly enough in the vignette now.
