### ISSUE TITLE
Accept tibbles and data.tables

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#51]
The `alfam2()` function should accept these, with either a crude approach (convert to data frame internally) or with fixes to any code that cannot handle these variations.

**Comment by sashahafner** [comment]
This is an example of crude approach https://github.com/sashahafner/jumbled/commit/0be37314cd2f11afdd8fc5bda0395429d6b2b850

**Comment by sashahafner** [comment]
Or this instead:

```
 dat[[i]][rout] <- approx(dat[[x]][-rout],...
```

See my own solution here: <https://stackoverflow.com/questions/75275143/extract-columns-using-a-character-variable-in-both-data-frames-and-data-tables>

**Comment by sashahafner** [comment]
I implemented a crude approach at some point. 
We have this around L 52:
```
    # Convert data.table to data.frame
    if (class(dat)[1] == 'data.table') {
      dat <- as.data.frame(dat)
    }
```

8316278df635649ff913144d044fe8ce4c96d3a0

**Comment by sashahafner** [comment]
```
    if (class(dat)[1] %in% c('data.table', 'tbl_df')) {
      dat <- as.data.frame(dat)
    }
 ```

**Comment by sashahafner** [comment]
How about tibbles?
And we should return the same structure that was given by the user.

**Comment by sashahafner** [comment]
Somewhere in the above commits I added conversion to data.table at end if that was input structure.

```
      if (dtinput) {
        dat <- data.table::data.table(dat)
      }
```

I guess this means we need to add data.table as a suggested package, right @ecoRoland2 ?

We could do the same for tibbles.

**Comment by sashahafner** [comment]
OK, so that would mean only adding `.datatable.aware = TRUE` somewhere (a new file in R I would think, for clarity). 
And `Imports:` in DESCRIPTION would get `data.table` but nothing would be added to NAMESPACE.
That seems simple.
Since only `data.table()` is used (no indexing) I am not concerned about all that info on `[.data.frame` and `[.data.table` in that section.

Alternatively, we could add `importFrom(data.table, data.table)` to NAMESPACE but I prefer to avoid forcing users to install data.table.

I am sure it isn't so simple for tibbles, so I am inclined to not provide this same functionality.
Users can always convert `alfam2()` output to a tibble or whatever after.

All seems OK?

**Comment by ecoRoland2** [comment]
I'm unclear what the purpose of the call to data.table is. I suspect you should simply remove it.

**Comment by sashahafner** [comment]
> I'm unclear what the purpose of the call to data.table is. I suspect you should simply remove it.

The purpose is to return a data.table when a user submits a data.table for the `dat` argument. Currently it is necessary to convert a submitted data.table to a data frame, because of the way we use variables for indexing, like this:

```
56:    if (any(is.na(dat[, incorp.name]))) {
...
71:    ct <- dat[dat$`__group` == i, time.name]
...
96:    dat[dat$`__group` == i & dat[, time.name] <= incorp.time[i], inc.ex] <- FALSE
```

In particular the use of a variable like time.name to refer to a column name doesn't with data.table but the `alfam2` function should accept data.tables.
So I opted for a simple solution where data.tables are converted to data frames.
But then it is convenient if the `alfam2` function returns a data.table in those cases. 
So that last step is what this is about.
See around these locations:

https://github.com/AU-BCE-EE/ALFAM2/blob/940a0c62c6977acfb2e588876df6126808fbcdb2/R/alfam2.R#L85
https://github.com/AU-BCE-EE/ALFAM2/blob/940a0c62c6977acfb2e588876df6126808fbcdb2/R/alfam2.R#L423

Maybe you have a better solution.
I am not crazy about rewriting all the indexing with some approach that works for both data.tables and data frames, like changing `dat[, incorp.name]` to `dat[[incorp.name]]`, in part because other cases are not so simple.
Of course `dat[, ..incorp.name]` won't work for data frames.
But maybe a conversion of the indexing lines is worth a try.

**Comment by ecoRoland2** [comment]
You shouldn't do all of that. Return a data.frame, document that and let the user use setDT if they need a data.table. The very slight convenience isn't worth the code complexity and a function should always return the same class regardless of input.

**Comment by sashahafner** [comment]
> You shouldn't do all of that. Return a data.frame, document that and let the user use setDT if they need a data.table. The very slight convenience isn't worth the code complexity and a function should always return the same class regardless of input.

OK, fine with me.
