### ISSUE TITLE
Submit to CRAN?

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#55]
A question for users.
Is there any good reason to try to get this package on CRAN?
I guess it would make installation easier.

**Comment by sashahafner** [comment]
Thinking about this again after a question from @ecoRoland2

**Comment by ecoRoland2** [comment]
There are several advantages, e.g.:

1. Ease of installation.
2. You benefit from the regular CRAN checks, which enforce compatibility with different R versions, including r-devel.
3. R-core often check potential changes in R against CRAN to see if they break anything.
4. Package maitainers of widely-used packages often check if changes break anything in their reverse-dependencies. 
5. You are forced to use best practices.
6. Users can be sure that the package is still being maintained as long as it is on CRAN.

Just as an anecdote: Two or three years ago I was asked by CRAN to resubmit my gasfluxes package because of a bug in knitr. If my package wasn't on CRAN I'd never known about that bug.

**Comment by sashahafner** [comment]
OK, I am planning on it.
I have been cleaning up the package, making checks more consistent etc. so that already proves point 5.

**Comment by sashahafner** [comment]
> In the help file:
> For each input variable that takes a nonnumeric argument, should the user be able to see which options can be put? for example a user cannot know the 'all' is a possibility for conf.int? (unless reading through the vignette).

Yes, right.

**Comment by sashahafner** [comment]
> L487 and other places unit on y-axis "kg/ha-h" don't you want "h^-1" or "/h"

No, I think that is OK.
kg/ha/h is ambiguous and I am too lazy to do superscripts.

> L684 consider other axis labels

Will do.

**Comment by JohannaPedersen** [comment]
I just had a look, and I agree with Frederik, it is nice work. It is comprehensive and the examples are good and well explained. 

A few points in random order: 
- ?ALFAM2 did not work just now when i tried it. The error message: 
            No documentation for ‘ALFAM2’ in specified packages and libraries:
            you could try ‘??ALFAM2’
- In your reference list the reference for the model is duplicated below reference [2]
- I guess section 3 will be updated once the package is on CRAN
- p12 has a reference that seems wrong: (¿=v1.2)
- (Now I know I try to make problems on purpose, but...) If I in example 5b write 'TRUE' for both app.mthd.bc and app.mthd.os i get results that is neither identical to app.mthd.bc or app.mthd.os or the default trailing hose. Maybe an warning if something like this is done?

Only got halfway trough the vignette, so maybe more another day.

**Comment by fdalby** [comment]
> * ?ALFAM2 did not work just now when i tried it. The error message

With CAPS it is not working for me either, but I think @sashahafner meant "?alfam2" which works for me.

**Comment by sashahafner** [comment]
> > * ?ALFAM2 did not work just now when i tried it. The error message
> 
> With CAPS it is not working for me either, but I think @sashahafner meant "?alfam2" which works for me.

Oops, you are right @fdalby 
Editing the comment.

**Comment by sashahafner** [comment]
At one time we had some aliases like `ALFAM2mod` and maybe `ALFAM2` but no longer.
There is still the potential for confusion with a package name of ALFAM2 and function `alfam2` but I think it is OK.
Do you agree? 
If not we can add `ALFAM2` as an alias.

**Comment by sashahafner** [comment]
> I just had a look, and I agree with Frederik, it is nice work. It is comprehensive and the examples are good and well explained.
> 
> A few points in random order:
> 
>     * ?ALFAM2 did not work just now when i tried it. The error message:
>       No documentation for ‘ALFAM2’ in specified packages and libraries:
>       you could try ‘??ALFAM2’


See above.


>     * In your reference list the reference for the model is duplicated below reference [2]

Oops. Fixed in 

>     * I guess section 3 will be updated once the package is on CRAN

Now starts with CRAN installation 
17080f952b9911ce94eba380491cae454d28055d


>     * p12 has a reference that seems wrong: (¿=v1.2)

Fixed with 5195b2dbe4975290ea16ca6e3b376859882fa6be

>     * (Now I know I try to make problems on purpose, but...) If I in example 5b write 'TRUE' for both app.mthd.bc and app.mthd.os i get results that is neither identical to app.mthd.bc or app.mthd.os or the default trailing hose. Maybe an warning if something like this is done?

Good idea.
We should add a check, also for incorporation.
See #67

**Comment by JohannaPedersen** [comment]
- Section 4.6, repetition of the word 'with': _.... running the model with with multiple..._
- Section 4.9: you refer to a 'book mentioned above', is it the one you mention in section 2? Maybe the link could be inserted here as well or make a reference for section 2. 
- Maybe some more names should be added to the acknowledgements :) 
- In the bottom of section 4.8, is it intentionally that the results from 'preduc2' is missing? 
![image](https://github.com/AU-BCE-EE/ALFAM2/assets/96528149/6d1164c4-60d2-4b1f-862b-3ae63ba77072)

**Comment by sashahafner** [comment]
> * Section 4.6, repetition of the word 'with': _.... running the model with with multiple..._
> 

Fixed

>     * Section 4.9: you refer to a 'book mentioned above', is it the one you mention in section 2? Maybe the link could be inserted here as well or make a reference for section 2.
> 

Fixed

>     * Maybe some more names should be added to the acknowledgements :)
> 

Just missing @fdalby right? Added.

>     * In the bottom of section 4.8, is it intentionally that the results from 'preduc2' is missing?
> 

No darn it. Seems to be a LaTeX problem. Working on it.

**Comment by ChHaeni** [comment]
@sashahafner I've opened PR #75 with a few change suggestions...

**Comment by sashahafner** [comment]
Thanks for all the corrections and suggestions.
I am getting close to submitting to CRAN.
So if you want to check anything else, best to do it today!
