### ISSUE TITLE
Warning or error when there are duplicate parameter names

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#57]

**Comment by sashahafner** [comment]
During parameter estimation I have sometimes made a mistake and submitted a parameter vector with duplicate elements (names) but different values.
`alfam2()` should return an error in this case.

**Comment by sashahafner** [comment]
Frederik, this might be a good simple one to start with.
Work in the dev branch.
I think it could be done with a line here:

https://github.com/sashahafner/ALFAM2/blob/13312475d23f81e90155f4e2bbf9d7e3f152b9a9/R/alfam2.R#L111

just after this block:

```

    # If pars was given as list, change to vector
    if(is.list(pars)) {
      pars <- unlist(pars)
    }
```

Could be done with something like `if (duplicated(names(pars)...` --> `stop()`.

Then you could add a test to `inst/tinytest/test_alfam2.R`

**Comment by fdalby** [comment]
Hi Sasha.
Sure I will look into this soon and return here.

**Comment by fdalby** [comment]
@sashahafner  I did take a look at this and added a stop() at the suggested place in alfam2.R. 

I added a few test lines in #inst/tinytest/test_alfam2.R, 
It should work with the edited alfam2.R in the dev branch, see example in #tests/duplicateNamesPars.R, (you can just delete that script again if you want)

**Comment by sashahafner** [comment]
Thanks @fdalby that does what was needed.
Here is a quick way to run all the tests:

```
tinytest::build_install_test()
```

With working directory "ALFAM2".
It doesn't give much info unless a test fails (at least I don't see how to get details, although the output is a tinytest object).
But that's fine.
