### ISSUE TITLE
Return confidence interval

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#60]
With bootstrap parameters this should be possible

**Comment by ecoRoland2** [comment]
But stress in the documentation, which sources of uncertainty are taken into account, and which not.

**Comment by sashahafner** [comment]
> But stress in the documentation, which sources of uncertainty are taken into account, and which not.

Sure.

**Comment by sashahafner** [comment]
I have added confidence interval calculations to `alfam2()` and would be happy to get some feedback @ecoRoland2 (or any other interested contributors, @JohannaPedersen @fdalby @ChHaeni ).

You can find a demo here:

<https://github.com/sashahafner/ALFAM2-applications/blob/main/conf_int/conf_int.pdf>

See around here for details in the help file:

https://github.com/AU-BCE-EE/ALFAM2/blob/44b6fa006d55b618940682211fdc34ad697e100c/man/alfam2.Rd#L118

The new arguments are:

```
  conf.int = NULL,
  pars.ci = NULL,
  n.ci = NULL,
  var.ci = 'er',
```

Any feedback is welcome but I am wondering about these issues:

* Is it a good decision to add this functionality (and 4 more arguments) to `alfam2()` instead of a new function? A new function would be so similar to `alfam2()` that I went with this option to extend instead. 
* Do the argument names seem OK? 
* Do they all seem necessary? (See [demo](https://github.com/sashahafner/ALFAM2-applications/blob/main/conf_int/conf_int.pdf))
* Should we split `conf.int`? Right now it 1) turns on/off CI calculation, 2) specifies the type of output (actually CIs or all underlying predictions, see demo), and 3) sets the confidence level. I prefer this over 2 or 3 arguments.

**Comment by sashahafner** [comment]
> But stress in the documentation, which sources of uncertainty are taken into account, and which not.

I need to work more on this.
Might be better in the details or note section instead of arguments.

**Comment by sashahafner** [comment]
> Could you have a default pars.ci, whenever CI is not null?

Yes, I agree we should.
At the moment there are values available for the default parameter set.
But ultimately this would be

```
  pars.ci = ALFAM2::alfam2pars03var,
```

For now I have added `_alpha`s to the set 3 parameter objects because they are not the final versions.

I think it should be OK to have a default value even though `confi.int=NULL` by default.

**Comment by JohannaPedersen** [comment]
I just read through the demo, I think it looks very nice with the CI options. Might come back with questions/comments later.

**Comment by sashahafner** [comment]
Problem when used with dummy var processing--dummy vars not returned.
See example below from vignette.

```
> datuc1 <- data.frame(group = 1:100, ctime = 168, TAN.app = 50, 
+                      app.mthd = 'bc', 
+                      man.dm = rnorm(100, mean = 8, sd = 2), 
+                      air.temp = 20, wind.2m = 3)
> quantile(datuc1$man.dm)
       0%       25%       50%       75%      100% 
 3.085756  6.555600  7.962371  9.201905 13.326079 
> preduc1 <- alfam2(datuc1, pars = alfam2pars03_alpha, app.name = 'TAN.app', 
+                   time.name = 'ctime', group = 'group',
+                   conf.int = 'all', pars.ci = alfam2pars03var_alpha)
User-supplied parameters are being used.
Warning message:
In alfam2(dat = dat, pars = pars, add.pars = add.pars, app.name = app.name,  :
  Running with 14 parameters. Dropped 11 with no match.
These secondary parameters have been dropped:
  app.rate.ni.f0
  man.source.pig.f0
  man.ph.r1
  rain.rate.r2
  man.ph.r3
  incorp.shallow.f4
  incorp.shallow.r3
  incorp.deep.f4
  incorp.deep.r3
  rain.rate.r5
  wind.sqrt.r1


> head(preduc1)
  group ctime  dt            f         s        e       ei         j        er
1     1   168 168 3.933637e-04 1.0374148 34.97135 34.97135 0.2081628 0.6994271
2     2   168 168 2.840996e-06 0.7575928 37.58311 37.58311 0.2237090 0.7516623
3     3   168 168 2.439665e-06 0.7535014 37.61672 37.61672 0.2239091 0.7523345
4     4   168 168 5.357732e-18 0.9857535 31.31783 31.31783 0.1864157 0.6263566
5     5   168 168 1.280352e-04 0.9391507 35.89716 35.89716 0.2136736 0.7179432
6     6   168 168 1.696143e-19 1.0481400 30.08885 30.08885 0.1791003 0.6017770
         f0         r1         r2          r3 f4         r5       jinst
1 0.9667494 0.04719176 0.02256409 0.002571463  1 0.01584893 0.002686237
2 0.9249897 0.07627761 0.02256409 0.002571463  1 0.01584893 0.001948338
3 0.9235277 0.07717470 0.02256409 0.002571463  1 0.01584893 0.001937789
4 0.6236470 0.23462545 0.02256409 0.002571463  1 0.01584893 0.002534828
5 0.9583166 0.05382073 0.02256409 0.002571463  1 0.01584893 0.002421882
6 0.5884317 0.25483167 0.02256409 0.002571463  1 0.01584893 0.002695253
>
```
