### ISSUE TITLE
Faster evaluation

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#61]
Some time before 1e336fd8f7a50623876a6bf9156544a812f9e887 I added a hidden `flatout` argument.
It was hidden to minimize risk, I suppose.
Should it be a proper argument?

**Comment by sashahafner** [comment]
I think I will do this. 
The option `flatout = TRUE` currently skips all or most of the checks that were added over time to avoid and identify errors.
So when using that option it is more common to have an error in the calculations (e.g., incorporation input problem) or get a useless error message.
This is drawback, but can be managed with a clear warning in the help file, along with a recommendation for users to compare output with and without the `flatout = TRUE` option to ensure the input is set up correctly. 

The advantage is an improvement in speed (10x compared to old R-only version, around 4x compared to Rcpp version without `flatout`).

**Comment by sashahafner** [comment]
Questions for collaborators @ChHaeni and @ecoRoland2:

1. Any concerns or suggestions for implementing this argument?
2. What are your thoughts on the argument name? Is "flat out" only an American term? ("at top speed or peak performance" from <https://www.merriam-webster.com/dictionary/flat-out>). Maybe "fast" is a better name for the new argument.

**Comment by ecoRoland2** [comment]
The name should be descriptive. If it allows skipping the assertion checks: `nochecks = FALSE`.

**Comment by sashahafner** [comment]
Now (around 68f50c033af348fb8e0e7c351533bdf4bbfabb4c) we have:

```
check = TRUE
```

which will check input arguments and more.

```
prep.incorp = TRUE
```
which does processing of inputs and parameters for incorporation.

```
warn = TRUE
```
which returns some warnings based on argument values or problems (and adjustments) to input data.

So without incorporation `alfam2(... check = FALSE)` runs slightly faster than the default.
But the real application is with incorporation, which is otherwise slow.
Fast approach is shown in vignette.
First sort out incorporation only (no emission calculation) with `value = "incorp"`.
Then run with `prep.incorp = FALSE`.

```
dat9c <- alfam2(dat9b, app.name = "TAN.app", time.name = "ct", 
                time.incorp = "t.incorp", group = "field", 
                warn = FALSE, value = "incorp")

pred9c <- alfam2(dat9c, app.name = 'TAN.app', time.name = 'ct', 
                   time.incorp = "t.incorp", group = 'field', 
                   warn = FALSE, prep.incorp = FALSE, check = FALSE)
```

I will ask you collaborators about argument names and behavior soon.
