### ISSUE TITLE
Return instantaneous flux as well?

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#63]
From the start the model function has always returned only average interval flux, calculated from cumulative emission.
But, thinking about other types of measurements like from wind tunnels, should we add instantaneous (point) flux values as well? 
Any thoughts @JohannaPedersen?

**Comment by JohannaPedersen** [comment]
I think it would be really nice! Maybe it doesn't have to be calculated by default, but it would be nice to have the option. 
(sorry for the late response)

**Comment by sashahafner** [comment]
Added in bbfa3144888e7386e61940f0ce4295a790cdf8fb v3.70 as column `jinst`. 
Not sure of a good name (maybe the other column names are not that good, for that matter).
I think it is OK to include without any option to exclude it in output.

**Comment by sashahafner** [comment]
Current name is `jinst`.
Any feedback?

**Comment by JohannaPedersen** [comment]
I think jinst is intuitive and fits with the other names. 
And I also think it is fine without an option to exclude. 

But I am not sure I understand https://github.com/AU-BCE-EE/ALFAM2/commit/bbfa3144888e7386e61940f0ce4295a790cdf8fb L 436, why is j > jinst in cases where flux is decreasing over time?

**Comment by sashahafner** [comment]
> So the statement in [bbfa314](https://github.com/AU-BCE-EE/ALFAM2/commit/bbfa3144888e7386e61940f0ce4295a790cdf8fb) L 436 ( Note that instantaneous flux (jinst) will always be lower than interval average flux.) is not correct, right? There can be examples where j < jinst, like the last point in your graphical explanation.

Oops, you are right!
Fixed now.
