### ISSUE TITLE
Check for multiple exclusive dummy variables = 1

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#67]
From @JohannaPedersen "If I in example 5b write 'TRUE' for both app.mthd.bc and app.mthd.os i get results that is neither identical to app.mthd.bc or app.mthd.os or the default trailing hose. Maybe an warning if something like this is done?"

Should also include for `man.source` and incorporation.

**Comment by sashahafner** [comment]
I just assigned you @JohannaPedersen to thank you for thinking of this :)

**Comment by sashahafner** [comment]
I'll help

**Comment by sashahafner** [comment]
Sorry @JohannaPedersen I just did this.
I wanted to do it before submitting to CRAN.
There are other issues to work on.

**Comment by sashahafner** [comment]
Can you test it?
Should throw an error.

**Comment by JohannaPedersen** [comment]
Did a test, worked well, will close issue.

**Comment by sashahafner** [comment]
This should only be done when `check = TRUE`
