### ISSUE TITLE
Checking object class

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#68]
I knew this suggestion existed somewhere.
Got it from package check with `R CMD BATCH check --as-cran`

```
Found if() conditions comparing class() to string:
File ‘ALFAM2/R/alfam2.R’: if (class(conf.int) == "character") ...
Use inherits() (or maybe is()) instead.
```

Probably needs to be sorted out in multiple places.

**Comment by ecoRoland2** [comment]
I don't think you need to check the class in

 ```
 if (inherits(dat, c('data.table', 'tbl_df'))) {
    dat <- as.data.frame(dat)
  } 
```

You should assert that `dat` inherits class "data.frame" before the conversion and error if it doesn't.

```
stopifnot("dat is not a dataframe" = inherits(dat, 'data.frame'))
dat <- as.data.frame(dat) #drop classes "tibble", "data.table", etc.
```

**Comment by ecoRoland2** [comment]
I haven't tried it but I believe a data.table should be handled just like a data.frame, i.e., no non-standard evaluation in `[`, if your package isn't "data.table aware" (even if the user has attached package data.table).

**Comment by sashahafner** [comment]
> I don't think you need to check the class in
> 
> ```
> if (inherits(dat, c('data.table', 'tbl_df'))) {
>    dat <- as.data.frame(dat)
>  } 
> ```

No, I guess not.
If `dat` is already a data frame `as.data.frame` does nothing.


> 
> You should assert that `dat` inherits class "data.frame" before the conversion and error if it doesn't.
> 
> ```
> stopifnot("dat is not a dataframe" = inherits(dat, 'data.frame'))
> dat <- as.data.frame(dat) #drop classes "tibble", "data.table", etc.
> ```

I guess I don't even need the `stopifnot` line because we already have this:

https://github.com/AU-BCE-EE/ALFAM2/blob/fbf1f4db2cdbe469594d70708b29807bbafe9bca/R/alfam2.R#L89

**Comment by sashahafner** [comment]
> I haven't tried it but I believe a data.table should be handled just like a data.frame, i.e., no non-standard evaluation in `[`, if your package isn't "data.table aware" (even if the user has attached package data.table).

Do you mean the `alfam2` function would run with a data.table for `dat` without conversion to a data frame?
No, it doesn't, because there are multiple places where column indexing is done using a variable.
This issue: <https://stackoverflow.com/questions/75275143/extract-columns-using-a-character-variable-in-both-data-frames-and-data-tables>.
One of the features of data.table that can be difficult to deal with, in my opinion.
Indexing with `[[` could be a solution but I have not worked on it.

But which is better, to return a data frame regardless of class of `dat` or to return object that is the same class as `dat`?
I thought from #51 [discussion[(https://github.com/AU-BCE-EE/ALFAM2/issues/51#issuecomment-2097908656) we were better off always returning a data frame.
