### ISSUE TITLE
Setup github actions for checks

### ISSUE THREAD

**Issue by ecoRoland2** [AU-BCE-EE/ALFAM2#69]
See https://r-hub.github.io/rhub/ or have a look at https://github.com/Rdatatable/data.table/blob/master/.github/workflows/R-CMD-check.yaml 

You should check the package at least on r-release and r-devel both on windows and linux before submitting to CRAN.

**Comment by sashahafner** [comment]
Thanks for that tip.
In the past I used to upload the package to win-builder <https://win-builder.r-project.org/> to try a couple additional versions of R.
But R-hub looks simpler, once set up.

**Comment by sashahafner** [comment]
This is great. 
Once setup it just takes `rhub_check()` to check on different systems/versions.

**Comment by sashahafner** [comment]
Reminder: It is the GitHub (pushed) version that is checked.
And has to be the master branch.

**Comment by ChHaeni** [comment]
> Reminder: It is the GitHub (pushed) version that is checked. And has to be the master branch.

I think it would make sense for dev branch, too - so differences would be caught at developement stage... (or maybe I misunderstood your last sentence...)

**Comment by sashahafner** [comment]
In case we want to use pdf vignettes again at some point, see here for a solution:
https://github.com/sashahafner/biogas/issues/63
