### ISSUE TITLE
Convert vignette to markdown

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#70]
The rhub machines/VMs don't seem to have LaTeX installed.
And anyway Rmd is simpler, and seems to be the preferred option now for packages.
Plus many people don't have a LaTeX compiler installed.
Too bad the output is uglier.

**Comment by ChHaeni** [comment]
I'm not at all familiar with GitHub actions, but I think you can install all you need on the fly...
I've copied this snipped of code from a different repo installing LaTeX during its action:

```
    steps:
      - name: Install LaTeX
        run: |
          sudo apt update
          sudo apt-get install texlive texlive-luatex texlive-latex-recommended texlive-latex-extra texlive-science
```

just in case you'd like the LaTeX version, too...

**Comment by sashahafner** [comment]
> I'm not at all familiar with GitHub actions, but I think you can install all you need on the fly... I've copied this snipped of action setup from a different repo installing LaTeX during its action:
> 
> ```
>     steps:
>       - name: Install LaTeX
>         run: |
>           sudo apt update
>           sudo apt-get install texlive texlive-luatex texlive-latex-recommended texlive-latex-extra texlive-science
> ```
> 
> just in case you'd like the LaTeX version, too...

Cool!
I suspected there might be an easy solution.
Thanks for figuring it out.
I'll probably stick with Markdown, because it is simpler.

**Comment by ecoRoland2** [comment]
And I think LaTeX is still needed to render the PDF.

**Comment by sashahafner** [comment]
> And I think LaTeX is still needed to render the PDF.

I've used html vignette. 
I think this is common now but am not sure.
