### ISSUE TITLE
Is argument `prep.dum` needed?

### ISSUE THREAD

**Issue by ChHaeni** [AU-BCE-EE/ALFAM2#72]
From the vignette:

> This data preparation option invoked by prep.dum = TRUE, which is the default.

Is there a use case for `prep.dum = FALSE`? Or could we remove this argument?

**Comment by sashahafner** [comment]
It sure would be nice to reduce the number of arguments in `alfam2`.
But I think I'd like to keep this one (or at least this functionality, to skip dummy variable prep) for:

1. Speed, when user has done pre-processing and wants to skip unnecessary stuff
2. If the user has no categorical predictors (or manually entered ones for some reason, perhaps new variables/parameters) and wants to avoid warning and possibility of mistakes

**Comment by ChHaeni** [comment]
ok, makes sense. closing the issue
