### ISSUE TITLE
Package testing devtools::load_all() problem

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#78]
On Windows, @JohannaPedersen gets an error when trying to use the package loaded with `devtools::load_all()`.
Seems to be related to Rcpp component somehow.

So `load_all()` seems to work, but when running `alfam2()` an error about the number of arguments sent to the Rcpp function is returned: something like 10 used but 7 expected.
But the function actually does have 10 arguments.
I cannot reproduce this problem on Ubuntu.
It isn't a package problem per se but makes development and testing difficult.
@ecoRoland2 @ChHaeni do you have any ideas?
We updated devtools and Rcpp.
@JohannaPedersen can you add the actual error message?

**Comment by sashahafner** [comment]
@JohannaPedersen do you have rtools installed?
You can get it here: https://cran.rstudio.com/bin/windows/Rtools/
That info is from here: https://support.posit.co/hc/en-us/articles/200486088-Using-Rcpp-with-the-RStudio-IDE

**Comment by ChHaeni** [comment]
Try to run `pkgbuild::clean_dll(path = path_to_alfam2)` before running `devtools::load_all(path = path_to_alfam2)`. I assume that the commited DLL file causes `load_all` to NOT recompile cpp code?

@sashahafner should we add these *.dll, *.o files to .gitignore?

**Comment by ecoRoland2** [comment]
> @sashahafner should we add these *.dll, *.o files to .gitignore?

You should definitely do that because these are platform dependent.

**Comment by ChHaeni** [comment]
> > @sashahafner should we add these *.dll, *.o files to .gitignore?
> 
> You should definitely do that because these are platform dependent.

PR #79 is open

**Comment by sashahafner** [comment]
Great, thanks guys!
@JohannaPedersen can you pull (dev OK, they are merged) and try again?

**Comment by JohannaPedersen** [comment]
Works now - thanks @sashahafner @ChHaeni @ecoRoland2  !

**Comment by sashahafner** [comment]
Great!
