### ISSUE TITLE
Mac OS vignette error

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/ALFAM2#83]
See checks here:

https://cran.rstudio.com/web/checks/check_results_ALFAM2.html

![image](https://github.com/AU-BCE-EE/ALFAM2/assets/35272876/0c30fce7-d4a1-4c95-9f14-b9b4903e5b25)

This is from an error *demonstration* here https://github.com/AU-BCE-EE/ALFAM2/blob/91d9850dc037905d6f35d8d2c3d2fcb06ad69887/vignettes/ALFAM2-start.Rmd#L817

I use `{r, error=TRUE}`, which seems to work OK for other operating systems.
Do we have to revert to `eval=FALSE`?

**Comment by ecoRoland2** [comment]
I'm just noticing this is r-oldrel. It is an option to simply depend on `R (≥ 4.4.0)`. I have done something similar when an R update changed how optimizers converged and my package produced different results / failed unit tests as a result.

**Comment by ecoRoland2** [comment]
I've asked about this on the R-package-devel mailing list. I believe the issue is related to this NEWS item for knitr 1.4.6:

> Package vignettes are tangled by default during R CMD check, per request from CRAN maintainers (d0d1b47). The consequence is that R CMD check will check R scripts tangled from vignettes by default, unless you set the environment variable _R_CHECK_VIGNETTES_SKIP_RUN_MAYBE_=true. Previously, knitr would skip tangling vignettes during R CMD check, because R scripts tangled from vignettes are not guaranteed to valid. With the skip undone, R CMD check may fail in places other than CRAN (because CRAN has set the environment variable).

**Comment by sashahafner** [comment]
Thanks @ecoRoland2

**Comment by ecoRoland2** [comment]
You should wait until Monday. I‘m hoping that the issue isn’t on our side or can be fixed easily.

**Comment by ecoRoland2** [comment]
Seems like adding `purl = FALSE` should fix this. See the thread on r-package-devel: https://stat.ethz.ch/pipermail/r-package-devel/2024q2/thread.html#10888

**Comment by sashahafner** [comment]
Great thank you!
Trying now.

**Comment by sashahafner** [comment]
Looks like this solved the problem, based on an rhub check.

**Comment by sashahafner** [comment]
Wait, now we get the same problem on r-devel on Linux!
I am switching to eval=FALSE.

**Comment by ecoRoland2** [comment]
The solution purl = FALSE should also work on linux.

**Comment by ecoRoland2** [comment]
You set `purl = TRUE`. Change that to `purl = FALSE`.

**Comment by sashahafner** [comment]
Ha, oops. 
OK, trying that.

**Comment by sashahafner** [comment]
Looks good everywhere now.
Submitting.
Thank you @ecoRoland2
